### ISSUE TITLE
Overloading worm skill doesn't unlock

### ISSUE THREAD

**Issue by LordVGames** [BrightBolt/AmpV2#4]
I've killed an overloading worm once in a normal run, and a few more times testing this, and none of the times did the overloading worm skill seem to unlock. There also seemed to be no error in the console when it happens.

**Comment by BrightBolt** [comment]
You have to land the final hit with voltaic bombardment; hope this helps!

**Comment by LordVGames** [comment]
That worked! I thought you just had to kill it to get it. The unlock text makes a bit more sense now.
