### ISSUE TITLE
Profile drop

### ISSUE THREAD

**Issue by Pandorys** [BrightBolt/AmpV2#5]
Hello, latest update kill my profile in game. If i rollback to previous version, profile again work
Привет, после последнего обновления слетает профиль игры . Но если я откатываю версию к предыдущей, то профиль снова определяется и все работает

**Comment by BrightBolt** [comment]
Hi,

Thanks for letting me know. Can you send me the output of the BepinEx log when you try to run the game with the latest update? To get that, first, just open up the game using the version of the mod that breaks the profile, then close the game and go to settings in R2Modman. Click "Browse profile folder". Then go into the BepinEx folder, and paste this file in a reply to this comment.

![image](https://github.com/BrightBolt/AmpV2/assets/81591421/4b217620-5dc1-4e5e-a05c-9edd6222b3e7)

**Comment by Pandorys** [comment]
[LogOutput.log](https://github.com/user-attachments/files/15594047/LogOutput.log)
![Screenshot_2](https://github.com/BrightBolt/AmpV2/assets/39304399/b7e24487-a937-45b5-907a-c4e368b9267d)
Screenshot - it's how it looks when the game loaded

**Comment by Hexiboo** [comment]
Can confirm that the same thing is happening for me since the most recent update, disabling the mod/downgrading to the previous version fixes it

**Comment by Pandorys** [comment]
Fixed in 2.1.2
